### PR TITLE
Add esm module support

### PR DESCRIPTION
**Pull request by shinobi5**
Fixes Issue #23

## Proposed Changes

- Add option to `bundler.js` script to generate an `esm` module output file
- Update original `umd` output file name to `beedle.umd.js` to distinguish between the different module types. Ideally, this file would be removed in the future and the `main` entry point updated to be the newly added `bundler.js` esm file.

## A brief summary of what the changes do

The changes proposed here improve the library by providing a `module` entry point into the package for tools like [@pikapkg/web](https://github.com/pikapkg/web) that generate and provide browser ready ES6 modules based on this entry point. It also means there will now be an [unpkg](https://unpkg.com/) browser ready `esm` option, while still providing the `umd` version for users consuming the package via unpkg with Nodejs.

Once enough Nodejs support is available for ES6 modules (see [node documentation](https://nodejs.org/api/esm.html) for further reading around this) then the `bundler.js` script and the package entry points can be updated to include only the `beedle.js` esm file. 

It's a forward looking approach while not affecting users that still need to consume the package with Nodejs in it's current state of support for ES6 modules.

### CODE REVIEW

**Comment by shinobi5** [comment]
I also noticed that the first test is currently failing. `Dispatch returns true if action was found`. It's returning `undefined` but expects `true`. I haven't looked into what the problem is and didn't touch it as it's not connected with the changes in this PR.

I thought I'd point it out though, but I'm happy to looking into it if you'd like.

**Comment by andybelldesign** [comment]
Oh good spot! I just looked at the [latest build](https://travis-ci.com/andybelldesign/beedle/builds/115693459) and you're absolutely right. Travis is very misleading on the build passing.

If you wouldn't mind looking (it's very kind of you to offer, thank you), that would be great. Shall we do that in a separate PR? 

The rest of this PR looks great, thank you.

**Comment by shinobi5** [comment]
Yeah that's no problem at all. I can look into it. I'll do that and set up another PR for it to keep it separate from the updates in this PR.

Do you want me to setup an issue for the failing test first? Or directly create a PR for it?

Happy either way, just let me know how you want to do it and I'll get that sorted.

**Comment by andybelldesign** [comment]
Yeh just do a PR for it. I'll merge this one. Thanks again, @shinobi5. I really appreciate your help.

**Pull request merged**
