### PR TITLE
Fix for multiple stateChange events #18

### PR DESCRIPTION
**Pull request by hparton**
Fixes Issue #18 
## Proposed Changes

- Implements fix proposed by interactiveRob to prevent multiple stateChange events firing when updating state.

### CODE REVIEW

**Comment by andybelldesign** [comment]
Cheers again, Harry. I'll give this a proper look early next week :)

**Comment by andybelldesign** [comment]
This looks great. Thanks very much for giving up your time for this :)

**Comment by christomonte11** [comment]
Thank you very much for your patience with me! 
Did git pull for beedle to get #20 on my box, however, did you also update the **non-minified beedle's in demo/basic and demo/advanced**? And btw, what about beedle-vue and beedle-react?
Regards, Micha

**Comment by andybelldesign** [comment]
No worries! I just need to go around updating the instances when I get some time :)

**Pull request merged**
